module.exports = {
  images: {
    domains: [
      "res-1.cloudinary.com",
      "res-2.cloudinary.com",
      "res-3.cloudinary.com",
      "res-4.cloudinary.com",
      "res-5.cloudinary.com",
      "res-6.cloudinary.com",
      "res-7.cloudinary.com",
      "res-8.cloudinary.com",
      "res-9.cloudinary.com",
      "res-10.cloudinary.com",
      "res-11.cloudinary.com",
      "res-12.cloudinary.com",
      "res-13.cloudinary.com",
      "res-14.cloudinary.com",
      "res-15.cloudinary.com",
      "res-16.cloudinary.com",
      "static.ghost.org",
    ],
  },
  target: "server",
  assetPrefix: process.env.PUBLIC_URL || "/",
};
